import Head from "next/head";
import Image from "next/image";
import { ReactNode } from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";
import ScrollToTop from "react-scroll-to-top";

type Props = {
  title: string;
  children: ReactNode[];
  id?: string;
  navbarDefaultCollapsed?: boolean
};

export default function Layout({ title, children, id, navbarDefaultCollapsed = false }: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/icons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/icons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/icons/favicon-16x16.png"
        />
      </Head>
      <Navbar defaultCollapsed={navbarDefaultCollapsed}/>
      <div id={id} className="pt-12 bg-white text-black font-['IBM_Plex_Mono']">
        {children}
      </div>
      <ScrollToTop smooth color="#1400FF" className=""/>

      {/* <Footer /> */}
    </>
  );
}
